# Generated by Django 4.2.16 on 2024-09-17 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_description_description_paragraph"),
    ]

    operations = [
        migrations.RenameField(
            model_name="description",
            old_name="device_id",
            new_name="device",
        ),
    ]
